# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-23 15:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateTimeField(default=datetime.datetime.now)),
                ('raw', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('職務類別', models.CharField(max_length=20)),
                ('學歷限制', models.CharField(max_length=20)),
                ('job', models.CharField(max_length=20)),
                ('聯絡人員', models.CharField(max_length=20)),
                ('需求人數', models.CharField(max_length=20)),
                ('工作經驗', models.CharField(max_length=20)),
                ('到職日期', models.CharField(max_length=20)),
                ('薪資', models.CharField(max_length=20)),
                ('地區', models.CharField(max_length=20)),
                ('科系限制', models.CharField(max_length=20)),
                ('工作時間', models.CharField(max_length=20)),
                ('休假制度', models.CharField(max_length=20)),
                ('工作地點', models.CharField(max_length=20)),
                ('實習時段', models.CharField(max_length=20)),
                ('職缺更新', models.CharField(max_length=20)),
                ('工作性質', models.CharField(max_length=20)),
                ('url', models.CharField(max_length=100)),
                ('工作說明', models.CharField(max_length=20)),
                ('身份類別', models.CharField(max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arrogant.Company')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='Job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arrogant.Job'),
        ),
    ]
