# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-23 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrogant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='休假制度',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='到職日期',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='地區',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='學歷限制',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='實習時段',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='工作地點',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='工作性質',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='工作時間',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='工作經驗',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='工作說明',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='科系限制',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='聯絡人員',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='職務類別',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='職缺更新',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='薪資',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='身份類別',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='需求人數',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
