# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-23 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrogant', '0002_auto_20170423_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='avatar',
            field=models.ImageField(default='media/politician.png', upload_to=''),
        ),
    ]
