# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-23 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrogant', '0003_job_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='avatar',
            field=models.ImageField(default='politician.png', upload_to=''),
        ),
    ]
