# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-24 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrogant', '0004_auto_20170424_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='fromWitchWeb',
            field=models.CharField(default='1111', max_length=10),
        ),
        migrations.AlterField(
            model_name='job',
            name='工作說明',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
