# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-24 08:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrogant', '0005_auto_20170424_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='job',
            name='工作時間',
            field=models.CharField(max_length=35, null=True),
        ),
    ]
