# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 09:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('infernoWeb', '0001_initial'),
        ('arrogant', '0006_auto_20170424_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='JobTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='LikesFromUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lfuauthor', to='infernoWeb.User')),
            ],
        ),
        migrations.CreateModel(
            name='PageLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='SkillTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('skill_field', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='job',
            name='fromWitchWeb',
        ),
        migrations.RemoveField(
            model_name='job',
            name='job',
        ),
        migrations.RemoveField(
            model_name='job',
            name='url',
        ),
        migrations.RemoveField(
            model_name='job',
            name='休假制度',
        ),
        migrations.RemoveField(
            model_name='job',
            name='到職日期',
        ),
        migrations.RemoveField(
            model_name='job',
            name='地區',
        ),
        migrations.RemoveField(
            model_name='job',
            name='學歷限制',
        ),
        migrations.RemoveField(
            model_name='job',
            name='實習時段',
        ),
        migrations.RemoveField(
            model_name='job',
            name='工作地點',
        ),
        migrations.RemoveField(
            model_name='job',
            name='工作性質',
        ),
        migrations.RemoveField(
            model_name='job',
            name='工作時間',
        ),
        migrations.RemoveField(
            model_name='job',
            name='工作經驗',
        ),
        migrations.RemoveField(
            model_name='job',
            name='工作說明',
        ),
        migrations.RemoveField(
            model_name='job',
            name='科系限制',
        ),
        migrations.RemoveField(
            model_name='job',
            name='聯絡人員',
        ),
        migrations.RemoveField(
            model_name='job',
            name='職務類別',
        ),
        migrations.RemoveField(
            model_name='job',
            name='職缺更新',
        ),
        migrations.RemoveField(
            model_name='job',
            name='薪資',
        ),
        migrations.RemoveField(
            model_name='job',
            name='身份類別',
        ),
        migrations.RemoveField(
            model_name='job',
            name='需求人數',
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, related_name='cmtauthor', to='infernoWeb.User'),
        ),
        migrations.AddField(
            model_name='company',
            name='area',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='company',
            name='banner',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='company',
            name='brand',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='company',
            name='description',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='company',
            name='path',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='company',
            name='公司規模',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='company',
            name='地址',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='company',
            name='資本額',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='job',
            name='has_salary_info',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='intern_tf',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='path',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='job',
            name='salary',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='comment',
            name='create',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='job',
            name='avatar',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.RemoveField(
            model_name='company',
            name='company',
        ),
        migrations.AlterUniqueTogether(
            name='company',
            unique_together=set([('brand', 'path')]),
        ),
        migrations.AddField(
            model_name='skilltag',
            name='Job',
            field=models.ManyToManyField(to='arrogant.Job'),
        ),
        migrations.AddField(
            model_name='pagelog',
            name='Job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arrogant.Job'),
        ),
        migrations.AddField(
            model_name='pagelog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ploguser', to='infernoWeb.User'),
        ),
        migrations.AddField(
            model_name='likesfromuser',
            name='comment',
            field=models.ManyToManyField(to='arrogant.Comment'),
        ),
        migrations.AddField(
            model_name='jobtag',
            name='Job',
            field=models.ManyToManyField(to='arrogant.Job'),
        ),
        migrations.AddField(
            model_name='category',
            name='Job',
            field=models.ManyToManyField(to='arrogant.Job'),
        ),
    ]
